### ISSUE TITLE
[Update] - 우측 추천 영화 리스트 인기도 정렬 출력

### ISSUE THREAD

**Issue by eliotjang** [eliotjang/Movolleh-Movie-Website#42]
### 우측 추천 영화 리스트 인기도 정렬 출력

TMDB Smilar API 기준으로 영화를 가져왔을 시 영화 개요, 출연진 및 감독의 이미지도 없는 인기가 없는 영화가 보이게 되어 page1 에서 20개의 데이터를 인기도 순으로 정렬하여 순서대로 6개 출력

### 이후 보완사항 논의 예정

page1의 20개 데이터가 아닌 page를 추가로 더 가져와서 +a의 데이터를 인기도 순으로 정렬하여 더 유명한 영화가 나오도록 변경할지 논의 필요

**Comment by KAPUIST** [comment]
해당 내용은 page 를 추가로 가져오지않고  첫 번째 페이지에 포함되어있는 20개 데이터내에서 정렬하기로 하였습니다.

**Comment by eliotjang** [comment]
네 확인했습니다
