### ISSUE TITLE
[Fix] - 리뷰 작성 버튼 클릭시 모달창으로 입력 구현 변경

### ISSUE THREAD

**Issue by eliotjang** [eliotjang/Movolleh-Movie-Website#53]
### 문제점 확인

- prompt 창으로 비밀번호를 입력하게되면 별표(숨김처리)가 나오지 않음
- prompt 창에서 입력칸은 1개만 나옴

### 대안점 논의

1. 비밀번호가 노출된 상태로 사용
2. 상세페이지 내에서 input 태그로 별표처리하여 비밀번호 입력

### 회의 후 결정 사항

- 작성, 수정을 모두 모달창으로 구현

### 문제점 이미지

![image](https://github.com/eliotjang/Movolleh-Movie-Website/assets/37320831/7d65fcbd-a5f6-4415-80e1-e9f78f774bdc)

**Comment by KAPUIST** [comment]
작성하기 는 놔두고 그아래로 리뷰리스트가 펼쳐 지는건 어떨까요???
그리고 수정 및 삭제만 모달로 띄우는것도 괜찮아보입니다!
