### ISSUE TITLE
[Update] 영화 목록 포스터 노출 범위 조정

### ISSUE THREAD

**Issue by 9r3dflam3** [eliotjang/Movolleh-Movie-Website#71]
### 검색 결과 출력 시
- [ ] 한 줄에 6개의 영화만 고정적으로 나오도록 수정
- [ ] 한 페이지에 18개의 영화만 나오도록 수정

**Comment by eliotjang** [comment]
랜딩 페이지에서는 태권님이 최신영화, 인기영화, 누적 리뷰 영화 순으로 작업중이니,
영화 제목을 검색을 했을때 검색된 영화에서만 나오게 하시면 됩니다.
